import { neon } from '@neondatabase/serverless'

const DB_URL = 'postgresql://neondb_owner:npg_yrN3Vo4lCfvR@ep-icy-sunset-aknj9kvt.c-3.us-west-2.aws.neon.tech/neondb?sslmode=require'
const sql = neon(DB_URL)

const RECIPES = [
  {
    id: '1',
    slug: 'miso-glazed-salmon',
    title: 'Miso-Glazed Salmon',
    subtitle: 'A weeknight hero',
    description: 'Sweet, savory, and done in 20 minutes. The miso glaze caramelizes under the broiler into something that feels far more impressive than the effort involved.',
    collection: 'Quick & Creative',
    cuisine: 'Japanese-inspired',
    moodTags: ['quick', 'weeknight', 'umami', 'healthy'],
    dietaryTags: ['gluten-free', 'dairy-free'],
    difficulty: 'Easy',
    prepTime: '5 min',
    cookTime: '15 min',
    totalTime: '20 min',
    servings: '2',
    gradient: 'from-orange-800 to-amber-600',
    aiGenerated: false,
    isFeatured: false,
    status: 'published',
    ingredients: [
      { group: 'Salmon', items: ['2 salmon fillets (about 6 oz each)', 'Salt and white pepper to taste'] },
      { group: 'Miso glaze', items: ['2 tbsp white miso paste', '1 tbsp mirin', '1 tbsp sake (or dry sherry)', '1 tsp sesame oil', '1 tsp honey'] },
      { group: 'To serve', items: ['Steamed rice', '2 scallions, thinly sliced', '1 tsp toasted sesame seeds'] },
    ],
    steps: [
      { title: 'Make the glaze', body: 'Whisk together the miso, mirin, sake, sesame oil, and honey in a small bowl until smooth.' },
      { title: 'Prep the salmon', body: 'Pat the salmon dry with paper towels. Season lightly with salt and white pepper. Place skin-side down on a foil-lined baking sheet.' },
      { title: 'Glaze and broil', body: 'Spread a generous layer of glaze over the top of each fillet. Broil on the top rack for 10 to 12 minutes until caramelized at the edges.' },
      { title: 'Rest and serve', body: 'Let the salmon rest for 2 minutes before serving over steamed rice. Scatter sliced scallions and sesame seeds over the top.' },
    ],
    nutrition: { calories: 420, protein: '38g', carbs: '12g', fat: '22g', fiber: '0g' },
    originStory: 'Miso-marinated fish is a cornerstone of Kyoto cuisine, where the technique of preserving fish in miso dates back centuries. This fast weeknight version captures the same depth of flavor in a fraction of the time.',
  },
  {
    id: '2',
    slug: 'lamb-kofta-with-tahini',
    title: 'Lamb Kofta with Tahini',
    subtitle: 'Street-food flavors at home',
    description: 'Fragrant with warm spices, charred at the edges, and served with a silky tahini sauce. This is the kind of food that makes you eat standing at the counter.',
    collection: 'Culinary Journeys',
    cuisine: 'Middle Eastern',
    moodTags: ['smoky', 'spiced', 'weekend', 'crowd-pleaser'],
    dietaryTags: ['gluten-free', 'dairy-free'],
    difficulty: 'Intermediate',
    prepTime: '15 min',
    cookTime: '20 min',
    totalTime: '35 min',
    servings: '4',
    gradient: 'from-stone-700 to-amber-800',
    aiGenerated: false,
    isFeatured: false,
    status: 'published',
    ingredients: [
      { group: 'Kofta', items: ['500g ground lamb', '1 small onion, grated', '3 garlic cloves, minced', '2 tsp ground cumin', '1 tsp ground coriander', '1 tsp smoked paprika', '1/2 tsp cinnamon', '1/4 tsp cayenne', 'Handful fresh parsley, finely chopped', 'Salt and black pepper'] },
      { group: 'Tahini sauce', items: ['4 tbsp tahini', '2 tbsp lemon juice', '1 garlic clove, grated', '4 tbsp cold water', 'Salt to taste'] },
      { group: 'To serve', items: ['Warm flatbreads or pita', 'Sliced cucumber and tomato', 'Fresh herbs (parsley, mint)', 'Lemon wedges'] },
    ],
    steps: [
      { title: 'Mix the kofta', body: 'Combine the lamb with the grated onion, garlic, spices, parsley, and a generous pinch of salt. Mix well with your hands. Refrigerate for at least 10 minutes.' },
      { title: 'Shape', body: 'Divide the mixture into 8 equal portions. Shape each into a long oval around a skewer or freehand into a sausage shape.' },
      { title: 'Make the tahini sauce', body: 'Whisk tahini with lemon juice and grated garlic. Add cold water a spoonful at a time until silky and pourable. Season with salt.' },
      { title: 'Grill', body: 'Grill on high heat for 4 to 5 minutes per side until deeply charred. Rest for 2 minutes.' },
      { title: 'Serve', body: 'Lay the kofta over warm flatbreads, drizzle with tahini sauce, and top with cucumber, tomato, herbs, and lemon.' },
    ],
    nutrition: { calories: 520, protein: '32g', carbs: '18g', fat: '36g', fiber: '2g' },
    originStory: 'Kofta appears across a vast arc of the world, from the Balkans through the Middle East to South Asia. The word comes from the Persian word for "pounded." This version draws from Levantine tradition, where lamb kofta on skewers over charcoal is a street-food staple.',
  },
  {
    id: '3',
    slug: 'brown-butter-financiers',
    title: 'Brown Butter Financiers',
    subtitle: 'The French bakery classic',
    description: 'A perfect financier has crisp, dark edges, a tender center, and a deep hazelnut perfume from the brown butter. Made in minutes, tastes like a patisserie.',
    collection: 'Baking Alchemy',
    cuisine: 'French',
    moodTags: ['baking', 'elegant', 'sweet', 'afternoon'],
    dietaryTags: ['vegetarian'],
    difficulty: 'Intermediate',
    prepTime: '15 min',
    cookTime: '30 min',
    totalTime: '45 min',
    servings: '12',
    gradient: 'from-yellow-700 to-amber-500',
    aiGenerated: false,
    isFeatured: false,
    status: 'published',
    ingredients: [
      { group: 'Batter', items: ['150g unsalted butter, plus extra for greasing', '150g powdered sugar, sifted', '60g almond flour', '50g all-purpose flour', '1/4 tsp fine sea salt', '4 egg whites (about 150g)', '1 tsp vanilla extract'] },
    ],
    steps: [
      { title: 'Brown the butter', body: 'Melt the butter in a light-colored saucepan over medium heat until it develops dark speckles and smells intensely nutty. Pour into a cool bowl immediately.' },
      { title: 'Mix the dry ingredients', body: 'Whisk together the powdered sugar, almond flour, all-purpose flour, and salt.' },
      { title: 'Combine', body: 'Add the egg whites and vanilla to the dry ingredients. Stir until just combined. Pour in the brown butter including all the dark speckles and stir.' },
      { title: 'Rest the batter', body: 'Refrigerate for at least 30 minutes, or overnight.' },
      { title: 'Bake', body: 'Preheat oven to 200C (400F). Grease a financier or mini muffin tin. Fill each mold three-quarters full. Bake 12 to 14 minutes until deeply golden. Cool 5 minutes then unmold.' },
    ],
    nutrition: { calories: 185, protein: '3g', carbs: '18g', fat: '12g', fiber: '0g' },
    originStory: 'Financiers were created in 19th-century Paris near the financial district. Their compact rectangular shape was designed to be eaten without getting crumbs on a suit.',
  },
  {
    id: '4',
    slug: 'slow-roasted-lamb-shoulder',
    title: 'Slow-Roasted Lamb Shoulder',
    subtitle: 'With pomegranate and herbs',
    description: 'Six hours in the oven, a lifetime on the table. The kind of recipe people remember long after the meal is over.',
    collection: 'Culinary Journeys',
    cuisine: 'Middle Eastern',
    moodTags: ['slow-cook', 'celebration', 'weekend', 'crowd-pleaser'],
    dietaryTags: ['gluten-free', 'dairy-free'],
    difficulty: 'Advanced',
    prepTime: '30 min',
    cookTime: '6 hrs',
    totalTime: '6 hrs 30 min',
    servings: '6 to 8',
    gradient: 'from-stone-600 to-amber-700',
    aiGenerated: false,
    isFeatured: true,
    status: 'published',
    ingredients: [
      { group: 'Lamb', items: ['1 bone-in lamb shoulder (about 2.5 kg)', '6 garlic cloves', '2 tsp cumin seeds', '2 tsp coriander seeds', '1 tsp smoked paprika', '1 tsp ground cinnamon', 'Handful fresh rosemary and thyme', '4 tbsp olive oil', 'Salt and black pepper'] },
      { group: 'Braising liquid', items: ['1 cup pomegranate juice', '1 cup chicken stock', '1 large onion, quartered', '400g can whole tomatoes'] },
      { group: 'To finish', items: ['Seeds of 1 pomegranate', 'Large handful fresh mint and parsley', '1 lemon, zested'] },
    ],
    steps: [
      { title: 'Spice and score', body: 'Score the lamb all over with deep cuts. Toast and grind the cumin and coriander. Mix with paprika, cinnamon, olive oil, salt, and pepper. Rub over the lamb, pressing into the cuts. Stuff garlic and herbs into the cuts. Refrigerate overnight if possible.' },
      { title: 'Build the braise', body: 'Preheat oven to 160C (325F). Place the onion, tomatoes, pomegranate juice, and stock in a deep roasting pan. Lay the lamb on top, fat side up.' },
      { title: 'Slow roast', body: 'Cover tightly with foil and roast for 5 hours. Remove the foil and increase heat to 200C (400F) for 30 to 45 minutes to caramelize the top.' },
      { title: 'Rest', body: 'Rest loosely covered for 20 minutes. Skim excess fat from the pan juices.' },
      { title: 'Serve', body: 'Pull the lamb apart directly in the pan. Plate and finish with pomegranate seeds, torn herbs, and lemon zest.' },
    ],
    nutrition: { calories: 680, protein: '52g', carbs: '14g', fat: '44g', fiber: '2g' },
    originStory: 'This version draws from Persian and Levantine traditions of braising lamb with pomegranate, a combination appearing in manuscripts dating to the Abbasid caliphate. The patience is the recipe.',
  },
  {
    id: '5',
    slug: 'pasta-e-fagioli',
    title: 'Pasta e Fagioli',
    subtitle: 'The classic Italian peasant soup',
    description: 'Not really a soup, not quite a pasta. Thick, starchy, richly flavored, impossibly cheap to make, and somehow more satisfying than most things that cost ten times as much.',
    collection: 'Seasonal Sensations',
    cuisine: 'Italian',
    moodTags: ['cozy', 'winter', 'comfort', 'budget-friendly'],
    dietaryTags: ['vegan', 'vegetarian'],
    difficulty: 'Easy',
    prepTime: '15 min',
    cookTime: '40 min',
    totalTime: '55 min',
    servings: '4 to 6',
    gradient: 'from-amber-700 to-orange-600',
    aiGenerated: false,
    isFeatured: false,
    status: 'published',
    ingredients: [
      { group: 'Base', items: ['4 tbsp olive oil', '1 large onion, finely diced', '3 celery stalks, finely diced', '2 medium carrots, finely diced', '6 garlic cloves, sliced', '1 sprig fresh rosemary', '2 dried bay leaves', '1/2 tsp chili flakes'] },
      { group: 'Beans and pasta', items: ['2 x 400g cans cannellini beans', '400g can whole peeled tomatoes', '1.2 liters vegetable stock', '200g ditalini or small tubular pasta'] },
      { group: 'To finish', items: ['Good olive oil', 'Freshly grated Parmesan or pecorino (optional)', 'Black pepper'] },
    ],
    steps: [
      { title: 'Build the soffritto', body: 'Warm a heavy pot with olive oil over low heat. Add onion, celery, and carrot with a pinch of salt. Cook very slowly for 20 minutes until completely soft and golden.' },
      { title: 'Add aromatics', body: 'Add the garlic, rosemary, bay leaves, and chili flakes. Cook for 2 minutes.' },
      { title: 'Add beans and tomatoes', body: 'Drain one can of beans. Add both cans, the tomatoes crushed by hand, and the stock. Simmer 20 minutes.' },
      { title: 'Blend partially', body: 'Remove rosemary and bay. Blend about a third of the soup in the pot using a stick blender.' },
      { title: 'Cook the pasta', body: 'Bring to a rolling simmer, add pasta, and cook until al dente, stirring frequently.' },
      { title: 'Finish and serve', body: 'Ladle into bowls, finish with olive oil and black pepper. Eat immediately.' },
    ],
    nutrition: { calories: 420, protein: '16g', carbs: '58g', fat: '14g', fiber: '10g' },
    originStory: 'Pasta e fagioli is one of Italy\'s oldest continuous recipes, appearing in Roman texts. For most of Italian history it was peasant food. The version that matters is always the one your grandmother made.',
  },
  {
    id: '6',
    slug: 'sourdough-country-loaf',
    title: 'Sourdough Country Loaf',
    subtitle: 'The weekend project',
    description: 'A proper open-crumb sourdough with a shatteringly crisp crust and deeply tangy flavor. This one takes two days and rewards every minute.',
    collection: 'Baking Alchemy',
    cuisine: 'French',
    moodTags: ['baking', 'weekend-project', 'artisan', 'slow'],
    dietaryTags: ['vegan', 'vegetarian'],
    difficulty: 'Advanced',
    prepTime: '30 min',
    cookTime: '45 min',
    totalTime: '2 days (with fermentation)',
    servings: '1 loaf',
    gradient: 'from-amber-900 to-yellow-600',
    aiGenerated: false,
    isFeatured: false,
    status: 'published',
    ingredients: [
      { group: 'Dough', items: ['450g bread flour (high protein)', '50g whole wheat flour', '375g water (~75% hydration)', '100g active starter (mature, at peak)', '10g fine sea salt'] },
    ],
    steps: [
      { title: 'Autolyse', body: 'Mix the flours and 350g of the water until no dry flour remains. Cover and rest 45 minutes.' },
      { title: 'Add starter and salt', body: 'Work in the starter by squeezing through your fingers. Add the salt dissolved in the remaining 25g water. Rest 30 minutes.' },
      { title: 'Bulk fermentation', body: 'Over 4 to 5 hours, perform 4 sets of stretch and folds every 30 minutes, then leave undisturbed until dough has grown 50 to 60 percent.' },
      { title: 'Shape', body: 'Pre-shape into a round, rest 20 minutes, then do your final shaping — build tension across the surface by dragging the dough toward you.' },
      { title: 'Cold proof', body: 'Place seam-side up in a floured banneton. Cover and refrigerate overnight (8 to 16 hours).' },
      { title: 'Score and bake', body: 'Preheat oven to 250C (480F) with a Dutch oven inside for 45 minutes. Score the cold dough, lower into the Dutch oven. Bake covered 20 minutes, then uncovered 20 to 25 minutes until deeply dark. Cool at least 1 hour before cutting.' },
    ],
    nutrition: { calories: 2400, protein: '80g', carbs: '480g', fat: '8g', fiber: '20g' },
    originStory: 'Sourdough is the oldest form of leavened bread, with evidence going back 14,000 years. The country loaf has its spiritual home in French artisan baking, popularized globally by American bakers like Chad Robertson of Tartine Bakery.',
  },
]

async function seed() {
  console.log('Seeding recipes...')
  for (const r of RECIPES) {
    await sql`
      INSERT INTO recipes (
        id, slug, title, subtitle, description, collection, cuisine,
        mood_tags, dietary_tags, difficulty, prep_time, cook_time, total_time,
        servings, ingredients, steps, nutrition, origin_story, gradient,
        status, ai_generated, is_featured, published_at
      ) VALUES (
        ${r.id}, ${r.slug}, ${r.title}, ${r.subtitle}, ${r.description},
        ${r.collection}::collection, ${r.cuisine},
        ${JSON.stringify(r.moodTags)}::jsonb, ${JSON.stringify(r.dietaryTags)}::jsonb,
        ${r.difficulty}::difficulty, ${r.prepTime}, ${r.cookTime}, ${r.totalTime},
        ${r.servings}, ${JSON.stringify(r.ingredients)}::jsonb,
        ${JSON.stringify(r.steps)}::jsonb, ${JSON.stringify(r.nutrition)}::jsonb,
        ${r.originStory}, ${r.gradient},
        ${r.status}::recipe_status, ${r.aiGenerated}, ${r.isFeatured}, NOW()
      )
      ON CONFLICT (id) DO NOTHING
    `
    console.log(`  + ${r.title}`)
  }
  console.log('Done.')
  process.exit(0)
}

seed().catch(e => { console.error(e); process.exit(1) })
